# complete code
apiVersion: v1
kind: ConfigMap
metadata:
  name: nebari-landing-config
data:
  forward-access-token: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: nebari-landing-secret
type: Opaque
data:
  forward-access-token: <base64 encoded value of "true">