// Package main is the documentation generator for nebari-landing.
//
// It reads internal/api/docs/swagger.json (regenerated by `make generate-docs`
// from swag annotations on the handlers) and injects two auto-generated
// sections into docs/api.md:
//
//	<!-- gendocs:apicard --> ... <picture> with dark/light SVG cards ... <!-- /gendocs:apicard -->
//	<!-- gendocs:api -->     ... endpoint table + per-endpoint detail   <!-- /gendocs:api -->
//
// Run via `go run ./cmd/gendocs`, `make docs`, or `go generate ./...`.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// methodOrder defines the canonical sort order for HTTP methods within a path.
var methodOrder = map[string]int{"get": 0, "post": 1, "put": 2, "patch": 3, "delete": 4}

func main() {
	root := mustRoot()

	specPath := filepath.Join(root, "internal", "api", "docs", "swagger.json")
	docPath := filepath.Join(root, "docs", "api.md")

	spec, err := loadSpec(specPath)
	if err != nil {
		fatalf("load %s: %v", specPath, err)
	}
	ops := flattenOps(spec)

	inject(docPath, "apicard", apicardBlock())
	inject(docPath, "api", renderAPI(spec, ops))
}

// ── injection ────────────────────────────────────────────────────────────────

// inject replaces the content between <!-- gendocs:name --> and <!-- /gendocs:name -->
// in the file at path. The markers themselves are preserved.
func inject(path, name, content string) {
	data, err := os.ReadFile(path)
	if err != nil {
		fatalf("read %s: %v", path, err)
	}
	open := fmt.Sprintf("<!-- gendocs:%s -->", name)
	closeT := fmt.Sprintf("<!-- /gendocs:%s -->", name)
	pat := regexp.MustCompile(regexp.QuoteMeta(open) + `[\s\S]*?` + regexp.QuoteMeta(closeT))
	if !strings.Contains(string(data), open) {
		fatalf("no %q marker found in %s — add the open/close markers in the file first", open, path)
	}
	// ReplaceAllLiteralString — not ReplaceAllString — because the rendered
	// content can contain $NAME (e.g. "Bearer $TOKEN" in curl examples) which
	// the regex engine would otherwise interpret as a backreference and erase.
	updated := pat.ReplaceAllLiteralString(string(data), open+"\n"+content+closeT)
	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
	fmt.Printf("  updated %-20s [%s]\n", relPath(path), name)
}

// ── spec loading ─────────────────────────────────────────────────────────────

// spec mirrors only the fields gendocs and genapicard care about.
type spec struct {
	Info struct {
		Title       string `json:"title"`
		Version     string `json:"version"`
		Description string `json:"description"`
	} `json:"info"`
	Servers []struct {
		URL string `json:"url"`
	} `json:"servers"`
	Paths map[string]map[string]operation `json:"paths"`
}

type operation struct {
	OperationID string `json:"operationId"`
	Summary     string `json:"summary"`
	Description string `json:"description"`
	Tags        []string
	// security is left untyped because we only check for presence of any entry.
	Security []map[string][]string `json:"security"`
}

func loadSpec(path string) (*spec, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var s spec
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil, fmt.Errorf("decode swagger.json: %w", err)
	}
	return &s, nil
}

// flatOp pairs a path + method with the underlying operation, ordered by
// document path order then HTTP method canonical order.
type flatOp struct {
	method string // "GET", "POST", ...
	path   string
	op     operation
}

func flattenOps(s *spec) []flatOp {
	paths := make([]string, 0, len(s.Paths))
	for p := range s.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var out []flatOp
	for _, p := range paths {
		methods := s.Paths[p]
		mkeys := make([]string, 0, len(methods))
		for m := range methods {
			mkeys = append(mkeys, m)
		}
		sort.Slice(mkeys, func(i, j int) bool {
			return methodOrder[mkeys[i]] < methodOrder[mkeys[j]]
		})
		for _, m := range mkeys {
			out = append(out, flatOp{method: strings.ToUpper(m), path: p, op: methods[m]})
		}
	}
	return out
}

// ── apicard block ────────────────────────────────────────────────────────────

// apicardBlock returns the <picture> element that points at the dark/light
// SVG cards generated by cmd/genapicard. Paths are relative to docs/.
func apicardBlock() string {
	return `<picture>
  <source media="(prefers-color-scheme: dark)"  srcset="assets/api-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="assets/api-light.svg">
  <img alt="nebari-landing API endpoint overview" src="assets/api-light.svg" width="1000">
</picture>
`
}

// ── API reference ────────────────────────────────────────────────────────────

func renderAPI(s *spec, ops []flatOp) string {
	server := "/api/v1"
	if len(s.Servers) > 0 {
		server = s.Servers[0].URL
	}

	var b bytes.Buffer
	b.WriteString("## Endpoints\n\n")
	b.WriteString("| Method | Path | Summary |\n")
	b.WriteString("|--------|------|---------|\n")
	for _, o := range ops {
		anchor := slugAnchor(o.method, o.path)
		b.WriteString(fmt.Sprintf("| `%s` | [`%s`](#%s) | %s |\n",
			o.method, o.path, anchor, o.op.Summary))
	}

	for _, o := range ops {
		b.WriteString("\n---\n\n")
		anchor := slugAnchor(o.method, o.path)
		b.WriteString(fmt.Sprintf("### <a name=%q></a>`%s %s`\n\n", anchor, o.method, o.path))
		if o.op.Summary != "" {
			b.WriteString(o.op.Summary + "\n\n")
		}
		if o.op.Description != "" {
			b.WriteString(o.op.Description + "\n\n")
		}
		b.WriteString(curlExample(o.method, o.path, server, requiresAuth(o.op)))
	}
	return b.String()
}

// curlExample emits a representative shell snippet for the operation. It
// includes a Bearer token placeholder when the operation declares any
// security requirement, and a JSON Content-Type for write methods.
func curlExample(method, path, server string, withAuth bool) string {
	base := "http://localhost:8080" + server

	var b bytes.Buffer
	b.WriteString("```sh\n")
	b.WriteString(fmt.Sprintf("curl -s -X %s %s%s", method, base, path))
	if withAuth {
		b.WriteString(" \\\n  -H 'Authorization: Bearer $TOKEN'")
	}
	if method == "POST" || method == "PUT" || method == "PATCH" {
		b.WriteString(" \\\n  -H 'Content-Type: application/json' \\\n  -d '{}'")
	}
	b.WriteString("\n```\n")
	return b.String()
}

func requiresAuth(op operation) bool {
	for _, sec := range op.Security {
		if len(sec) > 0 {
			return true
		}
	}
	return false
}

// slugAnchor mirrors GitHub's <a name="…"> convention used in tempo. Every
// non-alphanumeric character is dropped from the path so the anchor matches
// the auto-generated heading IDs.
func slugAnchor(method, path string) string {
	clean := strings.NewReplacer("/", "", "{", "", "}", "").Replace(path)
	return strings.ToLower(method) + "-" + strings.TrimLeft(clean, "-")
}

// ── utilities ────────────────────────────────────────────────────────────────

func mustRoot() string {
	cwd, err := os.Getwd()
	if err != nil {
		fatalf("getwd: %v", err)
	}
	// Walk up looking for go.mod so the tool works whether invoked from the
	// repo root, the cmd/ directory, or via `go generate`.
	for dir := cwd; dir != "/" && dir != ""; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
	}
	fatalf("could not find go.mod walking up from %s", cwd)
	return ""
}

func relPath(p string) string {
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, p); err == nil {
			return rel
		}
	}
	return p
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gendocs: "+format+"\n", args...)
	os.Exit(1)
}
