// Copyright 2026, OpenTeams.
// SPDX-License-Identifier: Apache-2.0

// Package notifications provides a Redis-backed store for platform notifications.
//
// Notifications are global records (they appear for every user). Per-user read
// state is tracked separately so a notification can be returned as read:true for
// one user and read:false for another without duplicating content.
//
// Redis data model:
//
//	nebari:notif:{id}       Hash  — all Notification fields
//	nebari:notifs           Sorted Set — score=unix-timestamp, member=notif ID
//	nebari:reads:{userID}   Set   — set of notif IDs the user has read
//
// Routes served by this store:
//
//	GET  /api/v1/notifications              -> List() + ReadSet(userID)
//	PUT  /api/v1/notifications/{id}/read    -> MarkRead(userID, id)
//	POST /api/v1/admin/notifications        -> Create(image, title, message)
package notifications

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
)

const (
	notifHashPrefix = "nebari:notif:"
	notifIndexKey   = "nebari:notifs"
	readsPrefix     = "nebari:reads:"
)

// ErrNotFound is returned when a notification ID does not exist.
var ErrNotFound = errors.New("notification not found")

// Notification is the canonical record stored in the database.
//
// When ServiceUID is non-empty, the notification is scoped to a specific
// NebariApp: REST list and WS broadcast paths apply the same canAccessPolicy
// reasoning against Visibility + RequiredGroups so only entitled callers see
// it. Untagged notifications (all three source-service fields empty) stay
// broadcast-to-all - welcome messages, feedback prompts, and admin-created
// announcements route through that path.
type Notification struct {
	// ID is the UUIDv4 primary key, generated by Create().
	ID string `json:"id"`
	// Image is an optional URL or icon identifier shown in the notification card.
	Image string `json:"image,omitempty"`
	// Title is the short heading of the notification.
	Title string `json:"title"`
	// Message is the body text of the notification.
	Message string `json:"message"`
	// CreatedAt is the UTC timestamp when the notification was created.
	CreatedAt time.Time `json:"createdAt"`

	// ServiceUID, when non-empty, ties this notification to a specific
	// NebariApp for per-caller access filtering. Producer sites (watcher
	// lifecycle events, health-checker transitions) populate this from the
	// source ServiceInfo; admin-created broadcast notifications leave it
	// empty and route through the fan-out-to-all path.
	ServiceUID string `json:"serviceUid,omitempty"`
	// Visibility mirrors ServiceInfo.Visibility for the source service:
	// "public" | "private" | "" (untagged). Consumed by canAccessPolicy.
	Visibility string `json:"visibility,omitempty"`
	// RequiredGroups mirrors ServiceInfo.RequiredGroups when the source
	// service is private. Consumed by canAccessPolicy.
	RequiredGroups []string `json:"requiredGroups,omitempty"`
}

// Draft is the input shape for CreateDraft. Wraps the notification body plus
// optional source-service metadata used for per-caller filtering. Producer
// sites (watcher, health-checker) fill in all three source-service fields;
// admin-created broadcasts leave them zero.
type Draft struct {
	Image   string
	Title   string
	Message string

	// ServiceUID, Visibility, RequiredGroups tie the notification to a
	// NebariApp for access-controlled delivery. Leaving all three zero
	// produces an untagged notification (broadcast-to-all).
	ServiceUID     string
	Visibility     string
	RequiredGroups []string
}

// Store is a Redis-backed store for notifications and per-user read state.
type Store struct {
	rdb       *redis.Client
	retention time.Duration
}

// NewStore returns a Store backed by the given Redis client.
// The client must already be configured; no connection is verified here.
func NewStore(rdb *redis.Client, retention time.Duration) *Store {
	return &Store{rdb: rdb, retention: retention}
}

// Close is a no-op; the Redis client lifetime is managed by the caller.
func (s *Store) Close() error { return nil }

// Create stores a new untagged notification (broadcast-to-all) and returns
// it. image may be empty. Kept as a thin wrapper around CreateDraft so the
// admin-created broadcast site (POST /api/v1/admin/notifications) does not
// have to name empty source-service fields.
func (s *Store) Create(image, title, message string) (*Notification, error) {
	return s.CreateDraft(Draft{Image: image, Title: title, Message: message})
}

// CreateDraft stores a new notification from a Draft. When the draft
// carries ServiceUID / Visibility / RequiredGroups, downstream REST and WS
// paths gate delivery per caller via canAccessPolicy. Empty source-service
// fields produce an untagged broadcast (equivalent to the legacy Create).
func (s *Store) CreateDraft(d Draft) (*Notification, error) {
	ctx := context.Background()
	n := &Notification{
		ID:             uuid.NewString(),
		Image:          d.Image,
		Title:          d.Title,
		Message:        d.Message,
		CreatedAt:      time.Now().UTC(),
		ServiceUID:     d.ServiceUID,
		Visibility:     d.Visibility,
		RequiredGroups: append([]string(nil), d.RequiredGroups...),
	}
	ts := n.CreatedAt.Format(time.RFC3339Nano)
	// requiredGroups is stored as a JSON-encoded string so the Redis hash
	// stays flat. Empty slice / nil marshal to "" via encodeGroups so
	// notifFromHash can detect "unset" cleanly.
	rg, err := encodeGroups(n.RequiredGroups)
	if err != nil {
		return nil, fmt.Errorf("notifications.CreateDraft: %w", err)
	}
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.HSet(ctx, notifKey(n.ID),
			"id", n.ID,
			"image", n.Image,
			"title", n.Title,
			"message", n.Message,
			"createdAt", ts,
			"serviceUid", n.ServiceUID,
			"visibility", n.Visibility,
			"requiredGroups", rg,
		)
		pipe.Expire(ctx, notifKey(n.ID), s.retention)
		pipe.ZAdd(ctx, notifIndexKey, redis.Z{
			Score:  float64(n.CreatedAt.UnixMilli()),
			Member: n.ID,
		})
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("notifications.CreateDraft: %w", err)
	}
	return n, nil
}

// Get retrieves a single notification by ID. Returns ErrNotFound when absent.
func (s *Store) Get(id string) (*Notification, error) {
	fields, err := s.rdb.HGetAll(context.Background(), notifKey(id)).Result()
	if err != nil {
		return nil, fmt.Errorf("notifications.Get %q: %w", id, err)
	}
	if len(fields) == 0 {
		return nil, ErrNotFound
	}
	return notifFromHash(fields)
}

// List returns all notifications, newest first.
func (s *Store) List() ([]*Notification, error) {
	ctx := context.Background()
	// ZRangeArgs with Rev:true returns IDs from highest score (newest) to lowest.
	ids, err := s.rdb.ZRangeArgs(ctx, redis.ZRangeArgs{
		Key:   notifIndexKey,
		Start: 0,
		Stop:  -1,
		Rev:   true,
	}).Result()
	if err != nil {
		return nil, fmt.Errorf("notifications.List index: %w", err)
	}
	if len(ids) == 0 {
		return []*Notification{}, nil
	}
	// Batch fetch with a pipeline.
	cmds := make([]*redis.MapStringStringCmd, len(ids))
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		for i, id := range ids {
			cmds[i] = pipe.HGetAll(ctx, notifKey(id))
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("notifications.List fetch: %w", err)
	}
	out := make([]*Notification, 0, len(ids))
	for _, cmd := range cmds {
		fields, err := cmd.Result()
		if err != nil || len(fields) == 0 {
			continue // skip missing / corrupt entries
		}
		n, err := notifFromHash(fields)
		if err != nil {
			continue
		}
		out = append(out, n)
	}
	return out, nil
}

// MarkRead records that userID has read notifID. Returns ErrNotFound when the
// notification ID does not exist. Calling MarkRead on an already-read
// notification is idempotent.
func (s *Store) MarkRead(userID, notifID string) error {
	ctx := context.Background()
	// Verify the notification exists.
	exists, err := s.rdb.Exists(ctx, notifKey(notifID)).Result()
	if err != nil {
		return fmt.Errorf("notifications.MarkRead exists: %w", err)
	}
	if exists == 0 {
		return ErrNotFound
	}
	if err := s.rdb.SAdd(ctx, readsKey(userID), notifID).Err(); err != nil {
		return fmt.Errorf("notifications.MarkRead sadd: %w", err)
	}
	return nil
}

// ReadSet returns a set of notification IDs that userID has already read.
// The returned map is safe to query with m[id]; absent keys are unread.
func (s *Store) ReadSet(userID string) (map[string]bool, error) {
	members, err := s.rdb.SMembers(context.Background(), readsKey(userID)).Result()
	if err != nil {
		return nil, fmt.Errorf("notifications.ReadSet %q: %w", userID, err)
	}
	out := make(map[string]bool, len(members))
	for _, m := range members {
		out[m] = true
	}
	return out, nil
}

// --- helpers ---

func notifKey(id string) string     { return notifHashPrefix + id }
func readsKey(userID string) string { return readsPrefix + userID }

func notifFromHash(f map[string]string) (*Notification, error) {
	t, err := time.Parse(time.RFC3339Nano, f["createdAt"])
	if err != nil {
		return nil, fmt.Errorf("parse createdAt: %w", err)
	}
	// Source-service fields are absent on legacy records written before this
	// migration; decodeGroups tolerates empty input and yields nil.
	groups, err := decodeGroups(f["requiredGroups"])
	if err != nil {
		return nil, fmt.Errorf("parse requiredGroups: %w", err)
	}
	return &Notification{
		ID:             f["id"],
		Image:          f["image"],
		Title:          f["title"],
		Message:        f["message"],
		CreatedAt:      t,
		ServiceUID:     f["serviceUid"],
		Visibility:     f["visibility"],
		RequiredGroups: groups,
	}, nil
}

// encodeGroups serializes RequiredGroups to a JSON string for storage in a
// Redis hash field. nil and empty slice both encode to "" so notifFromHash
// can round-trip them identically.
func encodeGroups(g []string) (string, error) {
	if len(g) == 0 {
		return "", nil
	}
	b, err := json.Marshal(g)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// decodeGroups parses a serialized RequiredGroups value. Empty input yields
// nil (untagged / legacy record).
func decodeGroups(s string) ([]string, error) {
	if s == "" {
		return nil, nil
	}
	var g []string
	if err := json.Unmarshal([]byte(s), &g); err != nil {
		return nil, err
	}
	return g, nil
}
