// Copyright 2026, OpenTeams.
// SPDX-License-Identifier: Apache-2.0

// Package notifications provides a Redis-backed store for platform notifications.
//
// Notifications are global records (they appear for every user). Per-user read
// state is tracked separately so a notification can be returned as read:true for
// one user and read:false for another without duplicating content.
//
// Redis data model:
//
//	nebari:notif:{id}       Hash  — all Notification fields
//	nebari:notifs           Sorted Set — score=unix-timestamp, member=notif ID
//	nebari:reads:{userID}   Set   — set of notif IDs the user has read
//
// Routes served by this store:
//
//	GET  /api/v1/notifications              -> List() + ReadSet(userID)
//	PUT  /api/v1/notifications/{id}/read    -> MarkRead(userID, id)
//	POST /api/v1/admin/notifications        -> Create(image, title, message)
package notifications

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
)

const (
	notifHashPrefix = "nebari:notif:"
	notifIndexKey   = "nebari:notifs"
	readsPrefix     = "nebari:reads:"
)

// ErrNotFound is returned when a notification ID does not exist.
var ErrNotFound = errors.New("notification not found")

// Notification is the canonical record stored in the database.
type Notification struct {
	// ID is the UUIDv4 primary key, generated by Create().
	ID string `json:"id"`
	// Image is an optional URL or icon identifier shown in the notification card.
	Image string `json:"image,omitempty"`
	// Title is the short heading of the notification.
	Title string `json:"title"`
	// Message is the body text of the notification.
	Message string `json:"message"`
	// CreatedAt is the UTC timestamp when the notification was created.
	CreatedAt time.Time `json:"createdAt"`
}

// Store is a Redis-backed store for notifications and per-user read state.
type Store struct {
	rdb *redis.Client
}

// NewStore returns a Store backed by the given Redis client.
// The client must already be configured; no connection is verified here.
func NewStore(rdb *redis.Client) *Store {
	return &Store{rdb: rdb}
}

// Close is a no-op; the Redis client lifetime is managed by the caller.
func (s *Store) Close() error { return nil }

// Create stores a new notification and returns it. image may be empty.
func (s *Store) Create(image, title, message string) (*Notification, error) {
	ctx := context.Background()
	n := &Notification{
		ID:        uuid.NewString(),
		Image:     image,
		Title:     title,
		Message:   message,
		CreatedAt: time.Now().UTC(),
	}
	ts := n.CreatedAt.Format(time.RFC3339Nano)
	_, err := s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.HSet(ctx, notifKey(n.ID),
			"id", n.ID,
			"image", n.Image,
			"title", n.Title,
			"message", n.Message,
			"createdAt", ts,
		)
		pipe.ZAdd(ctx, notifIndexKey, redis.Z{
			Score:  float64(n.CreatedAt.UnixMilli()),
			Member: n.ID,
		})
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("notifications.Create: %w", err)
	}
	return n, nil
}

// Get retrieves a single notification by ID. Returns ErrNotFound when absent.
func (s *Store) Get(id string) (*Notification, error) {
	fields, err := s.rdb.HGetAll(context.Background(), notifKey(id)).Result()
	if err != nil {
		return nil, fmt.Errorf("notifications.Get %q: %w", id, err)
	}
	if len(fields) == 0 {
		return nil, ErrNotFound
	}
	return notifFromHash(fields)
}

// List returns all notifications, newest first.
func (s *Store) List() ([]*Notification, error) {
	ctx := context.Background()
	// ZREVRANGE returns IDs from highest score (newest) to lowest.
	ids, err := s.rdb.ZRevRange(ctx, notifIndexKey, 0, -1).Result()
	if err != nil {
		return nil, fmt.Errorf("notifications.List index: %w", err)
	}
	if len(ids) == 0 {
		return []*Notification{}, nil
	}
	// Batch fetch with a pipeline.
	cmds := make([]*redis.MapStringStringCmd, len(ids))
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		for i, id := range ids {
			cmds[i] = pipe.HGetAll(ctx, notifKey(id))
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("notifications.List fetch: %w", err)
	}
	out := make([]*Notification, 0, len(ids))
	for _, cmd := range cmds {
		fields, err := cmd.Result()
		if err != nil || len(fields) == 0 {
			continue // skip missing / corrupt entries
		}
		n, err := notifFromHash(fields)
		if err != nil {
			continue
		}
		out = append(out, n)
	}
	return out, nil
}

// MarkRead records that userID has read notifID. Returns ErrNotFound when the
// notification ID does not exist. Calling MarkRead on an already-read
// notification is idempotent.
func (s *Store) MarkRead(userID, notifID string) error {
	ctx := context.Background()
	// Verify the notification exists.
	exists, err := s.rdb.Exists(ctx, notifKey(notifID)).Result()
	if err != nil {
		return fmt.Errorf("notifications.MarkRead exists: %w", err)
	}
	if exists == 0 {
		return ErrNotFound
	}
	if err := s.rdb.SAdd(ctx, readsKey(userID), notifID).Err(); err != nil {
		return fmt.Errorf("notifications.MarkRead sadd: %w", err)
	}
	return nil
}

// ReadSet returns a set of notification IDs that userID has already read.
// The returned map is safe to query with m[id]; absent keys are unread.
func (s *Store) ReadSet(userID string) (map[string]bool, error) {
	members, err := s.rdb.SMembers(context.Background(), readsKey(userID)).Result()
	if err != nil {
		return nil, fmt.Errorf("notifications.ReadSet %q: %w", userID, err)
	}
	out := make(map[string]bool, len(members))
	for _, m := range members {
		out[m] = true
	}
	return out, nil
}

// --- helpers ---

func notifKey(id string) string   { return notifHashPrefix + id }
func readsKey(userID string) string { return readsPrefix + userID }

func notifFromHash(f map[string]string) (*Notification, error) {
	t, err := time.Parse(time.RFC3339Nano, f["createdAt"])
	if err != nil {
		return nil, fmt.Errorf("parse createdAt: %w", err)
	}
	return &Notification{
		ID:        f["id"],
		Image:     f["image"],
		Title:     f["title"],
		Message:   f["message"],
		CreatedAt: t,
	}, nil
}
