// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "accessrequests.AccessRequest": {
                "properties": {
                    "id": {
                        "description": "ID is the UUIDv4 primary key, generated by Create().",
                        "type": "string"
                    },
                    "message": {
                        "description": "Message is an optional free-text note from the requester.",
                        "type": "string"
                    },
                    "requestedAt": {
                        "description": "RequestedAt is the UTC timestamp when the request was created.",
                        "type": "string"
                    },
                    "resolvedAt": {
                        "description": "ResolvedAt is set when the request is approved or denied.",
                        "type": "string"
                    },
                    "resolvedBy": {
                        "description": "ResolvedBy is the stable issuer+subject identity key of the admin who approved or denied the request.",
                        "type": "string"
                    },
                    "resolvedByIssuer": {
                        "description": "ResolvedByIssuer is the immutable JWT issuer of the resolving admin.",
                        "type": "string"
                    },
                    "resolvedBySubject": {
                        "description": "ResolvedBySubject is the immutable JWT subject of the resolving admin.",
                        "type": "string"
                    },
                    "resolvedByUsername": {
                        "description": "ResolvedByUsername is mutable display metadata from the resolving admin's preferred_username.",
                        "type": "string"
                    },
                    "serviceName": {
                        "description": "ServiceName is the human-readable name of the service at request time.",
                        "type": "string"
                    },
                    "serviceUID": {
                        "description": "ServiceUID is the Kubernetes UID of the target NebariApp.",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/accessrequests.Status"
                    },
                    "userEmail": {
                        "description": "UserEmail is included when present in the JWT claims.",
                        "type": "string"
                    },
                    "userID": {
                        "description": "UserID is the caller's stable issuer+subject identity key.",
                        "type": "string"
                    },
                    "userIssuer": {
                        "description": "UserIssuer is the immutable JWT issuer recorded at request time.",
                        "type": "string"
                    },
                    "userSubject": {
                        "description": "UserSubject is the immutable JWT subject recorded at request time.",
                        "type": "string"
                    },
                    "username": {
                        "description": "Username is mutable display metadata from preferred_username.",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "accessrequests.Status": {
                "description": "Status is the current lifecycle state.",
                "enum": [
                    "pending",
                    "approved",
                    "denied"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "StatusPending",
                    "StatusApproved",
                    "StatusDenied"
                ]
            },
            "api.CallerIdentityResponse": {
                "properties": {
                    "authenticated": {
                        "type": "boolean"
                    },
                    "email": {
                        "type": "string"
                    },
                    "groups": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "api.CreateNotificationBody": {
                "properties": {
                    "image": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "api.HealthResponse": {
                "properties": {
                    "status": {
                        "example": "healthy",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "api.NotificationItem": {
                "properties": {
                    "createdAt": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "image": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "read": {
                        "type": "boolean"
                    },
                    "title": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "api.PinsResponse": {
                "properties": {
                    "pins": {
                        "description": "Pins is the ordered list of pinned services (cached ServiceInfo snapshots).",
                        "items": {
                            "$ref": "#/components/schemas/cache.ServiceInfo"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "uids": {
                        "description": "UIDs lists exactly which UIDs are stored, including those that are no longer\ncached (e.g. the NebariApp was deleted).",
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "api.RequestAccessBody": {
                "properties": {
                    "message": {
                        "description": "optional free-text note from the user",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "api.ServiceResponse": {
                "properties": {
                    "services": {
                        "items": {
                            "$ref": "#/components/schemas/api.ServiceView"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "type": "object"
            },
            "api.ServiceView": {
                "properties": {
                    "category": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "description": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "image": {
                        "type": "string"
                    },
                    "imageDark": {
                        "type": "string"
                    },
                    "imageLight": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "pinned": {
                        "type": "boolean"
                    },
                    "status": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "api.WSTicketResponse": {
                "properties": {
                    "ticket": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "cache.HealthStatus": {
                "properties": {
                    "lastCheck": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "status": {
                        "description": "healthy, unhealthy, unknown",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "cache.ServiceInfo": {
                "properties": {
                    "category": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "displayName": {
                        "type": "string"
                    },
                    "health": {
                        "$ref": "#/components/schemas/cache.HealthStatus"
                    },
                    "icon": {
                        "type": "string"
                    },
                    "iconDark": {
                        "type": "string"
                    },
                    "iconLight": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "namespace": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "integer"
                    },
                    "requiredGroups": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "uid": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    },
                    "visibility": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "notifications.Notification": {
                "properties": {
                    "createdAt": {
                        "description": "CreatedAt is the UTC timestamp when the notification was created.",
                        "type": "string"
                    },
                    "id": {
                        "description": "ID is the UUIDv4 primary key, generated by Create().",
                        "type": "string"
                    },
                    "image": {
                        "description": "Image is an optional URL or icon identifier shown in the notification card.",
                        "type": "string"
                    },
                    "message": {
                        "description": "Message is the body text of the notification.",
                        "type": "string"
                    },
                    "requiredGroups": {
                        "description": "RequiredGroups mirrors ServiceInfo.RequiredGroups when the source\nservice is private. Consumed by canAccessPolicy.",
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "serviceUid": {
                        "description": "ServiceUID, when non-empty, ties this notification to a specific\nNebariApp for per-caller access filtering. Producer sites (watcher\nlifecycle events, health-checker transitions) populate this from the\nsource ServiceInfo; admin-created broadcast notifications leave it\nempty and route through the fan-out-to-all path.",
                        "type": "string"
                    },
                    "title": {
                        "description": "Title is the short heading of the notification.",
                        "type": "string"
                    },
                    "visibility": {
                        "description": "Visibility mirrors ServiceInfo.Visibility for the source service:\n\"public\" | \"private\" | \"\" (untagged). Consumed by canAccessPolicy.",
                        "type": "string"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "description": "Keycloak-issued JWT, sent as \"Bearer \u003ctoken\u003e\".",
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/admin/access-requests": {
            "get": {
                "description": "Returns access requests across the cluster. Admin-only — caller's JWT must include the configured admin group.",
                "parameters": [
                    {
                        "description": "Filter by status: pending, approved, or denied",
                        "in": "query",
                        "name": "status",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/accessrequests.AccessRequest"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Forbidden: admin group required"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Access request feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List access requests (admin)",
                "tags": [
                    "admin"
                ]
            }
        },
        "/admin/access-requests/{id}/{action}": {
            "put": {
                "description": "Action is encoded in the URL: PUT .../{id}/approve or .../{id}/deny. Approving also adds the user to the service's required Keycloak groups when a Keycloak admin client is configured.",
                "parameters": [
                    {
                        "description": "Access request ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "approve | deny",
                        "in": "path",
                        "name": "action",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/accessrequests.AccessRequest"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Bad request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Forbidden: admin group required"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Request not found"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Access request feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Approve or deny an access request (admin)",
                "tags": [
                    "admin"
                ]
            }
        },
        "/admin/notifications": {
            "post": {
                "description": "Creates a new platform-wide notification visible to all users via GET /notifications. Admin-only.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/api.CreateNotificationBody",
                                        "summary": "body",
                                        "description": "Notification payload"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Notification payload",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/notifications.Notification"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Bad request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Forbidden: admin group required"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Notifications feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Create a notification (admin)",
                "tags": [
                    "admin"
                ]
            }
        },
        "/caller-identity": {
            "get": {
                "description": "Echoes the resolved JWT claims for the caller. Returns {\"authenticated\": false} when no valid token is present.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/api.CallerIdentityResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get the caller's identity",
                "tags": [
                    "identity"
                ]
            }
        },
        "/categories": {
            "get": {
                "description": "Returns the distinct set of category labels currently advertised by services in the cache. Public — no auth required.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "items": {
                                            "type": "string"
                                        },
                                        "type": "array"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    }
                },
                "summary": "List service categories",
                "tags": [
                    "services"
                ]
            }
        },
        "/health": {
            "get": {
                "description": "Returns {\"status\":\"healthy\"} as long as the server is up. Does not check downstream dependencies.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/api.HealthResponse"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Liveness probe",
                "tags": [
                    "health"
                ]
            }
        },
        "/notifications": {
            "get": {
                "description": "Returns all platform notifications. When the caller is authenticated, each item's \"read\" flag reflects that user's per-notification read state; for anonymous callers all items are reported as unread.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/api.NotificationItem"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Internal server error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List notifications",
                "tags": [
                    "notifications"
                ]
            }
        },
        "/notifications/{id}/read": {
            "put": {
                "description": "Marks the specified notification as read for the calling user. Idempotent — returns 204 even if already read.",
                "parameters": [
                    {
                        "description": "Notification ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Bad request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Notification not found"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Notifications feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Mark a notification as read",
                "tags": [
                    "notifications"
                ]
            }
        },
        "/pins": {
            "get": {
                "description": "Returns the caller's pinned services. UIDs is the raw stored list; Pins is the subset still resolvable in the live cache (so deleted services are gracefully filtered out).",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/api.PinsResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Internal server error"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Pins feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List the caller's pins",
                "tags": [
                    "pins"
                ]
            }
        },
        "/pins/{uid}": {
            "delete": {
                "description": "PUT pins the service; DELETE unpins. Both operations are idempotent. The UID is the NebariApp UID exposed at status.serviceDiscovery.",
                "parameters": [
                    {
                        "description": "NebariApp UID",
                        "in": "path",
                        "name": "uid",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "UID is required"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Internal server error"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Pins feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Pin or unpin a service",
                "tags": [
                    "pins"
                ]
            },
            "put": {
                "description": "PUT pins the service; DELETE unpins. Both operations are idempotent. The UID is the NebariApp UID exposed at status.serviceDiscovery.",
                "parameters": [
                    {
                        "description": "NebariApp UID",
                        "in": "path",
                        "name": "uid",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "UID is required"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Internal server error"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Pins feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Pin or unpin a service",
                "tags": [
                    "pins"
                ]
            }
        },
        "/services": {
            "get": {
                "description": "Returns the union of public services plus any private services the caller may access based on their JWT groups.\nAnonymous callers see public services only; bearer-token callers additionally see private services they have access to. The \"pinned\" flag reflects the caller's own pin list (always false for anonymous).",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/api.ServiceResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List discoverable services",
                "tags": [
                    "services"
                ]
            }
        },
        "/services/{id}": {
            "get": {
                "description": "Returns the service if the caller may access it. Anonymous callers may only fetch public services; private services require a JWT whose groups intersect the service's required groups.",
                "parameters": [
                    {
                        "description": "Service UID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/api.ServiceView"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Service ID is required"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Forbidden"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Service not found"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Get a service by UID",
                "tags": [
                    "services"
                ]
            }
        },
        "/services/{id}/request_access": {
            "post": {
                "description": "Requires authentication. Creates a pending access request for the caller against the named service; an admin then approves or denies via /admin/access-requests/{id}/{approve|deny}.",
                "parameters": [
                    {
                        "description": "Service UID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/api.RequestAccessBody",
                                        "summary": "body",
                                        "description": "Optional message from the requester"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "Optional message from the requester"
                },
                "responses": {
                    "202": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/accessrequests.AccessRequest"
                                }
                            }
                        },
                        "description": "Accepted"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Bad request"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Service not found"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method not allowed"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Pending request already exists"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Access request feature not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Request access to a private service",
                "tags": [
                    "services"
                ]
            }
        },
        "/ws": {
            "get": {
                "description": "Upgrade to WebSocket. Server pushes JSON envelopes for service add/update/delete and new notifications. Auth is required before the upgrade: send ` + "`" + `Authorization: Bearer \u003ctoken\u003e` + "`" + ` or pass ` + "`" + `?ticket=\u003cid\u003e` + "`" + ` from POST /api/v1/ws-ticket (browsers must use the ticket path).",
                "parameters": [
                    {
                        "description": "Single-use ticket from POST /api/v1/ws-ticket (required for browser clients)",
                        "in": "query",
                        "name": "ticket",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "101": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Switching Protocols"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "WebSocket: real-time service + notification events",
                "tags": [
                    "websocket"
                ]
            }
        },
        "/ws-ticket": {
            "post": {
                "description": "Mints a short-lived (~30 s) single-use ticket the browser passes as ` + "`" + `?ticket=\u003cid\u003e` + "`" + ` on the WebSocket upgrade request, since the WS spec forbids sending an Authorization header on the upgrade. Requires a Bearer JWT.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/api.WSTicketResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    },
                    "405": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "Method Not Allowed"
                    },
                    "501": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        },
                        "description": "WebSocket ticket exchange not configured"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Issue a single-use WebSocket ticket",
                "tags": [
                    "websocket"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/api/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Title:            "Nebari Landing Page API",
	Description:      "Service-discovery and notifications API consumed by the nebari-landing SPA.\nSpec is published only when the server is started with --enable-docs (off in production).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
