// Regenerate frontend/src/mocks/generated/handlers.ts from the OpenAPI 3.1
// spec at internal/api/docs/swagger.json.
//
// The generated handlers return a deterministic example value for the 200/201
// response of each operation. They are intentionally dumb: the stateful
// behaviors (pin/unpin, mark-read, request_access, admin actions) are layered
// on top in src/mocks/handlers.ts.
//
// Run via `npm run mocks:generate` (also wired into `make docs`).

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SPEC_PATH = resolve(__dirname, "../../internal/api/docs/swagger.json");
const OUT_PATH = resolve(__dirname, "../src/mocks/generated/handlers.ts");
const API_BASE = "/api/v1";

type JsonObject = { [k: string]: unknown };
type Schema = JsonObject;

type Operation = {
  responses?: Record<string, { content?: Record<string, { schema?: Schema }> }>;
};

type PathItem = Partial<Record<"get" | "post" | "put" | "delete" | "patch", Operation>>;

type Spec = {
  paths: Record<string, PathItem>;
  components?: { schemas?: Record<string, Schema> };
};

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8")) as Spec;
const schemas = spec.components?.schemas ?? {};

// Build a deterministic example for a schema, following $refs and respecting
// enums / types. Visited refs short-circuit to avoid infinite recursion.
function exampleFor(schema: Schema | undefined, visited = new Set<string>()): unknown {
  if (!schema || typeof schema !== "object") return null;

  if (typeof schema.$ref === "string") {
    const ref = schema.$ref;
    if (visited.has(ref)) return null;
    const name = ref.replace(/^#\/components\/schemas\//, "");
    const target = schemas[name];
    if (!target) return null;
    return exampleFor(target, new Set([...visited, ref]));
  }

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return schema.enum[0];
  }

  if (Array.isArray(schema.oneOf) && schema.oneOf.length > 0) {
    return exampleFor(schema.oneOf[0] as Schema, visited);
  }
  if (Array.isArray(schema.allOf) && schema.allOf.length > 0) {
    const merged: JsonObject = {};
    for (const part of schema.allOf as Schema[]) {
      const v = exampleFor(part, visited);
      if (v && typeof v === "object" && !Array.isArray(v)) Object.assign(merged, v);
    }
    return merged;
  }

  switch (schema.type) {
    case "string":
      if (schema.format === "date-time") return new Date(0).toISOString();
      if (schema.format === "uuid") return "00000000-0000-0000-0000-000000000000";
      return "";
    case "integer":
    case "number":
      return 0;
    case "boolean":
      return false;
    case "array":
      return [];
    case "object":
    default: {
      const out: JsonObject = {};
      const props = (schema.properties ?? {}) as Record<string, Schema>;
      for (const [name, prop] of Object.entries(props)) {
        out[name] = exampleFor(prop, visited);
      }
      return out;
    }
  }
}

function pickResponseSchema(op: Operation): Schema | undefined {
  const responses = op.responses ?? {};
  for (const code of ["200", "201", "202", "204"]) {
    const r = responses[code];
    if (r?.content?.["application/json"]?.schema) {
      return r.content["application/json"].schema;
    }
  }
  return undefined;
}

// Convert OpenAPI path templating ("/services/{id}") into MSW's path param
// syntax ("/services/:id").
function toMswPath(path: string): string {
  return API_BASE + path.replace(/\{(\w+)\}/g, ":$1");
}

type GeneratedHandler = {
  method: "get" | "post" | "put" | "delete" | "patch";
  path: string;
  mswPath: string;
  body: unknown;
  status: number;
};

const handlers: GeneratedHandler[] = [];
const methods = ["get", "post", "put", "delete", "patch"] as const;

for (const [path, item] of Object.entries(spec.paths)) {
  for (const method of methods) {
    const op = item[method];
    if (!op) continue;
    const schema = pickResponseSchema(op);
    const body = schema ? exampleFor(schema) : null;
    const status = op.responses?.["201"] ? 201 : op.responses?.["204"] ? 204 : 200;
    handlers.push({ method, path, mswPath: toMswPath(path), body, status });
  }
}

handlers.sort((a, b) => (a.path === b.path ? a.method.localeCompare(b.method) : a.path.localeCompare(b.path)));

const lines: string[] = [];
lines.push("// Code generated by frontend/scripts/generate-msw-handlers.ts. DO NOT EDIT.");
lines.push("// Source: internal/api/docs/swagger.json. Regenerate with `make docs` or");
lines.push("// `npm --prefix frontend run mocks:generate`.");
lines.push("");
lines.push('import { http, HttpResponse } from "msw";');
lines.push("");
lines.push("export const generatedHandlers = [");
for (const h of handlers) {
  const bodyLiteral = JSON.stringify(h.body, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "    " + line))
    .join("\n");
  if (h.status === 204) {
    lines.push(`  http.${h.method}(${JSON.stringify(h.mswPath)}, () => new HttpResponse(null, { status: 204 })),`);
  } else {
    lines.push(`  http.${h.method}(${JSON.stringify(h.mswPath)}, () =>`);
    lines.push(`    HttpResponse.json(${bodyLiteral}${h.status === 200 ? "" : `, { status: ${h.status} }`})`);
    lines.push(`  ),`);
  }
}
lines.push("];");
lines.push("");

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, lines.join("\n"), "utf8");

console.log(`generated ${handlers.length} handlers → ${OUT_PATH}`);
