// Copyright 2026, OpenTeams.
// SPDX-License-Identifier: Apache-2.0

// Package accessrequests provides a Redis-backed store for service access
// requests submitted by users. Access requests flow through these endpoints:
//
//	POST /api/v1/services/{id}/request_access
//	  → Create() — status: pending; O(1) dedup via SET NX
//
//	GET  /api/v1/admin/access-requests          → ListAll() / ListPending()
//	PUT  /api/v1/admin/access-requests/{id}/approve → UpdateStatus(id, Approved, by)
//	PUT  /api/v1/admin/access-requests/{id}/deny    → UpdateStatus(id, Denied,   by)
//
// Redis data model:
//
//	nebari:ar:{id}                Hash  — all AccessRequest fields
//	nebari:ar:all                 Sorted Set — score=unix-ms, member=id
//	nebari:ar:pending             Sorted Set — score=unix-ms, member=id (pending only)
//	nebari:ar:user:{userID}       Sorted Set — score=unix-ms, member=id (per-user)
//	nebari:ar:dedup:{userID}:{svcUID}  String key (SET NX) — O(1) pending dedup
package accessrequests

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
)

const (
	arHashPrefix  = "nebari:ar:"
	arAllKey      = "nebari:ar:all"
	arPendingKey  = "nebari:ar:pending"
	arUserPrefix  = "nebari:ar:user:"
	arDedupPrefix = "nebari:ar:dedup:"
)

// Status represents the lifecycle state of an AccessRequest.
type Status string

const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusDenied   Status = "denied"
)

// AccessRequest records a user's request to access a private service.
type AccessRequest struct {
	// ID is the UUIDv4 primary key, generated by Create().
	ID string `json:"id"`
	// ServiceUID is the Kubernetes UID of the target NebariApp.
	ServiceUID string `json:"serviceUID"`
	// ServiceName is the human-readable name of the service at request time.
	ServiceName string `json:"serviceName"`
	// UserID is the caller's preferred_username (or JWT sub fallback).
	UserID string `json:"userID"`
	// UserEmail is included when present in the JWT claims.
	UserEmail string `json:"userEmail,omitempty"`
	// Message is an optional free-text note from the requester.
	Message string `json:"message,omitempty"`
	// Status is the current lifecycle state.
	Status Status `json:"status"`
	// RequestedAt is the UTC timestamp when the request was created.
	RequestedAt time.Time `json:"requestedAt"`
	// ResolvedAt is set when the request is approved or denied.
	ResolvedAt *time.Time `json:"resolvedAt,omitempty"`
	// ResolvedBy is the admin username who approved or denied the request.
	ResolvedBy string `json:"resolvedBy,omitempty"`
}

// Sentinel errors returned by Store operations.
var (
	// ErrDuplicatePending is returned by Create when a pending request already
	// exists for the same (userID, serviceUID) pair.
	ErrDuplicatePending = errors.New("a pending access request already exists for this user and service")

	// ErrNotFound is returned when a request ID does not exist in the store.
	ErrNotFound = errors.New("access request not found")
)

// Store is a Redis-backed persistent store for AccessRequest records.
type Store struct {
	rdb *redis.Client
}

// NewStore returns a Store backed by the given Redis client.
// The client must already be configured; no connection is verified here.
func NewStore(rdb *redis.Client) *Store {
	return &Store{rdb: rdb}
}

// Close is a no-op; the Redis client lifetime is managed by the caller.
func (s *Store) Close() error { return nil }

// Create stores a new pending access request.
//
// Returns ErrDuplicatePending without writing if a pending request already
// exists for the same (userID, serviceUID) pair — O(1) via SET NX.
func (s *Store) Create(serviceUID, serviceName, userID, userEmail, message string) (*AccessRequest, error) {
	ctx := context.Background()
	req := &AccessRequest{
		ID:          uuid.NewString(),
		ServiceUID:  serviceUID,
		ServiceName: serviceName,
		UserID:      userID,
		UserEmail:   userEmail,
		Message:     message,
		Status:      StatusPending,
		RequestedAt: time.Now().UTC(),
	}
	dedupKey := arDedupKey(userID, serviceUID)
	// Atomic dedup: SET NX returns true only if the key did not exist.
	set, err := s.rdb.SetNX(ctx, dedupKey, req.ID, 0).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.Create dedup: %w", err)
	}
	if !set {
		return nil, ErrDuplicatePending
	}
	score := float64(req.RequestedAt.UnixMilli())
	ts := req.RequestedAt.Format(time.RFC3339Nano)
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.HSet(ctx, arKey(req.ID),
			"id", req.ID,
			"serviceUID", req.ServiceUID,
			"serviceName", req.ServiceName,
			"userID", req.UserID,
			"userEmail", req.UserEmail,
			"message", req.Message,
			"status", string(req.Status),
			"requestedAt", ts,
		)
		z := redis.Z{Score: score, Member: req.ID}
		pipe.ZAdd(ctx, arAllKey, z)
		pipe.ZAdd(ctx, arPendingKey, z)
		pipe.ZAdd(ctx, arUserKey(userID), z)
		return nil
	})
	if err != nil {
		// Best-effort cleanup of the dedup key so the user can retry.
		_ = s.rdb.Del(ctx, dedupKey)
		return nil, fmt.Errorf("accessrequests.Create write: %w", err)
	}
	return req, nil
}

// Get retrieves a single access request by ID.
// Returns ErrNotFound when the ID does not exist.
func (s *Store) Get(id string) (*AccessRequest, error) {
	fields, err := s.rdb.HGetAll(context.Background(), arKey(id)).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.Get %q: %w", id, err)
	}
	if len(fields) == 0 {
		return nil, ErrNotFound
	}
	return arFromHash(fields)
}

// ListAll returns every stored access request, newest first.
func (s *Store) ListAll() ([]*AccessRequest, error) {
	return s.listFromIndex(arAllKey)
}

// ListPending returns only requests with status=pending, newest first.
func (s *Store) ListPending() ([]*AccessRequest, error) {
	return s.listFromIndex(arPendingKey)
}

// ListForUser returns all requests submitted by userID, newest first.
func (s *Store) ListForUser(userID string) ([]*AccessRequest, error) {
	return s.listFromIndex(arUserKey(userID))
}

func (s *Store) listFromIndex(indexKey string) ([]*AccessRequest, error) {
	ctx := context.Background()
	ids, err := s.rdb.ZRevRange(ctx, indexKey, 0, -1).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.list %q: %w", indexKey, err)
	}
	if len(ids) == 0 {
		return []*AccessRequest{}, nil
	}
	cmds := make([]*redis.MapStringStringCmd, len(ids))
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		for i, id := range ids {
			cmds[i] = pipe.HGetAll(ctx, arKey(id))
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("accessrequests.list fetch: %w", err)
	}
	out := make([]*AccessRequest, 0, len(ids))
	for _, cmd := range cmds {
		fields, err := cmd.Result()
		if err != nil || len(fields) == 0 {
			continue
		}
		r, err := arFromHash(fields)
		if err != nil {
			continue
		}
		out = append(out, r)
	}
	return out, nil
}

// UpdateStatus transitions an access request to Approved or Denied and records
// who performed the resolution. Returns the updated request.
// Returns ErrNotFound when the ID does not exist.
func (s *Store) UpdateStatus(id string, status Status, resolvedBy string) (*AccessRequest, error) {
	ctx := context.Background()
	// Fetch the full record so we can clean up the dedup key.
	fields, err := s.rdb.HGetAll(ctx, arKey(id)).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.UpdateStatus get: %w", err)
	}
	if len(fields) == 0 {
		return nil, ErrNotFound
	}
	req, err := arFromHash(fields)
	if err != nil {
		return nil, err
	}
	now := time.Now().UTC()
	req.Status = status
	req.ResolvedAt = &now
	req.ResolvedBy = resolvedBy
	resolvedAtStr := now.Format(time.RFC3339Nano)
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.HSet(ctx, arKey(id),
			"status", string(status),
			"resolvedAt", resolvedAtStr,
			"resolvedBy", resolvedBy,
		)
		// Remove from pending index; keep in all + user indexes.
		pipe.ZRem(ctx, arPendingKey, id)
		// Release the dedup lock so a future request can be created.
		pipe.Del(ctx, arDedupKey(req.UserID, req.ServiceUID))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("accessrequests.UpdateStatus write: %w", err)
	}
	return req, nil
}

// --- helpers ---

func arKey(id string) string              { return arHashPrefix + id }
func arUserKey(userID string) string      { return arUserPrefix + userID }
func arDedupKey(userID, svcUID string) string {
	return arDedupPrefix + userID + ":" + svcUID
}

func arFromHash(f map[string]string) (*AccessRequest, error) {
	reqAt, err := time.Parse(time.RFC3339Nano, f["requestedAt"])
	if err != nil {
		return nil, fmt.Errorf("parse requestedAt: %w", err)
	}
	req := &AccessRequest{
		ID:          f["id"],
		ServiceUID:  f["serviceUID"],
		ServiceName: f["serviceName"],
		UserID:      f["userID"],
		UserEmail:   f["userEmail"],
		Message:     f["message"],
		Status:      Status(f["status"]),
		RequestedAt: reqAt,
	}
	if s := f["resolvedAt"]; s != "" {
		t, err := time.Parse(time.RFC3339Nano, s)
		if err != nil {
			return nil, fmt.Errorf("parse resolvedAt: %w", err)
		}
		req.ResolvedAt = &t
	}
	req.ResolvedBy = f["resolvedBy"]
	return req, nil
}
