// Copyright 2026, OpenTeams.
// SPDX-License-Identifier: Apache-2.0

// Package accessrequests provides a Redis-backed store for service access
// requests submitted by users. Access requests flow through these endpoints:
//
//	POST /api/v1/services/{id}/request_access
//	  → Create() — status: pending; O(1) dedup via SET NX
//
//	GET  /api/v1/admin/access-requests          → ListAll() / ListPending()
//	PUT    /api/v1/admin/access-requests/{id}/approve → Resolve(id, Approved, audit)
//	PUT    /api/v1/admin/access-requests/{id}/deny    → Resolve(id, Denied,   audit)
//	DELETE /api/v1/admin/access-requests/{id}         → Resolve(id, Revoked,  audit)
//
// Redis data model:
//
//	nebari:ar:{id}                Hash  — all AccessRequest fields
//	nebari:ar:all                 Sorted Set — score=unix-ms, member=id
//	nebari:ar:pending             Sorted Set — score=unix-ms, member=id (pending only)
//	nebari:ar:user:{userID}       Sorted Set — score=unix-ms, member=id (per-user subject)
//	nebari:ar:dedup:{userID}:{svcUID}  String key (SET NX) — O(1) pending dedup
//	nebari:ar:active:{userID}:{svcUID} String key (TTL) — current active entitlement ID
package accessrequests

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/redis/go-redis/v9"
)

const (
	arHashPrefix   = "nebari:ar:"
	arAllKey       = "nebari:ar:all"
	arPendingKey   = "nebari:ar:pending"
	arUserPrefix   = "nebari:ar:user:"
	arDedupPrefix  = "nebari:ar:dedup:"
	arActivePrefix = "nebari:ar:active:"
)

const deleteActiveIfMatchesScript = `
if redis.call("GET", KEYS[1]) == ARGV[1] then
	return redis.call("DEL", KEYS[1])
end
return 0
`

// Status represents the lifecycle state of an AccessRequest.
type Status string

const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusDenied   Status = "denied"
	StatusRevoked  Status = "revoked"
)

// AccessRequest records a user's request to access a private service.
type AccessRequest struct {
	// ID is the UUIDv4 primary key, generated by Create().
	ID string `json:"id"`
	// ServiceUID is the Kubernetes UID of the target NebariApp.
	ServiceUID string `json:"serviceUID"`
	// ServiceName is the human-readable name of the service at request time.
	ServiceName string `json:"serviceName"`
	// TargetOwner identifies the service owner/definition for audit. Today this
	// is the target NebariApp namespace/name.
	TargetOwner string `json:"targetOwner,omitempty"`
	// UserID is the caller's stable JWT subject (or preferred_username fallback
	// in development/test modes that do not provide sub).
	UserID string `json:"userID"`
	// UserEmail is included when present in the JWT claims.
	UserEmail string `json:"userEmail,omitempty"`
	// Message is an optional free-text note from the requester.
	Message string `json:"message,omitempty"`
	// Status is the current lifecycle state.
	Status Status `json:"status"`
	// RequestedAt is the UTC timestamp when the request was created.
	RequestedAt time.Time `json:"requestedAt"`
	// ResolvedAt is set when the request is approved, denied, or revoked.
	ResolvedAt *time.Time `json:"resolvedAt,omitempty"`
	// ResolvedBy is the stable user ID of the admin who approved, denied, or revoked the request.
	ResolvedBy string `json:"resolvedBy,omitempty"`
	// ResolvedByName is the display name of the admin when present in the JWT.
	ResolvedByName string `json:"resolvedByName,omitempty"`
	// ResolvedByEmail is the email of the admin when present in the JWT.
	ResolvedByEmail string `json:"resolvedByEmail,omitempty"`
	// ExpiresAt is set for approved landing-owned entitlements. Once this time
	// passes, the approval no longer grants service access.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// Resolution records the admin action used to resolve or revoke an access
// request. ExpiresAt is meaningful only when Status is StatusApproved.
type Resolution struct {
	Status          Status
	ResolvedBy      string
	ResolvedByName  string
	ResolvedByEmail string
	ExpiresAt       *time.Time
}

// Sentinel errors returned by Store operations.
var (
	// ErrDuplicatePending is returned by Create when a pending request already
	// exists for the same (userID, serviceUID) pair.
	ErrDuplicatePending = errors.New("a pending access request already exists for this user and service")

	// ErrActiveEntitlement is returned by Create when the same user already has
	// an active approval for the same service.
	ErrActiveEntitlement = errors.New("an active access entitlement already exists for this user and service")

	// ErrNotFound is returned when a request ID does not exist in the store.
	ErrNotFound = errors.New("access request not found")

	// ErrInvalidStatus is returned when a resolution status is unsupported.
	ErrInvalidStatus = errors.New("invalid access request status")
)

// Store is a Redis-backed persistent store for AccessRequest records.
type Store struct {
	rdb *redis.Client
}

// NewStore returns a Store backed by the given Redis client.
// The client must already be configured; no connection is verified here.
func NewStore(rdb *redis.Client) *Store {
	return &Store{rdb: rdb}
}

// Close is a no-op; the Redis client lifetime is managed by the caller.
func (s *Store) Close() error { return nil }

// Create stores a new pending access request.
//
// Returns ErrDuplicatePending without writing if a pending request already
// exists for the same (userID, serviceUID) pair — O(1) via SET NX.
func (s *Store) Create(serviceUID, serviceName, userID, userEmail, message string) (*AccessRequest, error) {
	return s.CreateWithOwner(serviceUID, serviceName, "", userID, userEmail, message)
}

// CreateWithOwner stores a new pending access request and records the target
// owner identifier for audit.
func (s *Store) CreateWithOwner(serviceUID, serviceName, targetOwner, userID, userEmail, message string) (*AccessRequest, error) {
	ctx := context.Background()
	req := &AccessRequest{
		ID:          uuid.NewString(),
		ServiceUID:  serviceUID,
		ServiceName: serviceName,
		TargetOwner: targetOwner,
		UserID:      userID,
		UserEmail:   userEmail,
		Message:     message,
		Status:      StatusPending,
		RequestedAt: time.Now().UTC(),
	}
	if activeID, err := s.rdb.Get(ctx, arActiveKey(userID, serviceUID)).Result(); err == nil && activeID != "" {
		return nil, ErrActiveEntitlement
	} else if err != nil && !errors.Is(err, redis.Nil) {
		return nil, fmt.Errorf("accessrequests.Create active entitlement: %w", err)
	}
	dedupKey := arDedupKey(userID, serviceUID)
	// Atomic dedup: SET NX returns OK only if the key did not exist.
	if err := s.rdb.SetArgs(ctx, dedupKey, req.ID, redis.SetArgs{
		Mode: "NX",
	}).Err(); err != nil {
		if errors.Is(err, redis.Nil) {
			return nil, ErrDuplicatePending
		}
		return nil, fmt.Errorf("accessrequests.Create dedup: %w", err)
	}
	score := float64(req.RequestedAt.UnixMilli())
	ts := req.RequestedAt.Format(time.RFC3339Nano)
	_, err := s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.HSet(ctx, arKey(req.ID),
			"id", req.ID,
			"serviceUID", req.ServiceUID,
			"serviceName", req.ServiceName,
			"targetOwner", req.TargetOwner,
			"userID", req.UserID,
			"userEmail", req.UserEmail,
			"message", req.Message,
			"status", string(req.Status),
			"requestedAt", ts,
		)
		z := redis.Z{Score: score, Member: req.ID}
		pipe.ZAdd(ctx, arAllKey, z)
		pipe.ZAdd(ctx, arPendingKey, z)
		pipe.ZAdd(ctx, arUserKey(userID), z)
		return nil
	})
	if err != nil {
		// Best-effort cleanup of the dedup key so the user can retry.
		_ = s.rdb.Del(ctx, dedupKey)
		return nil, fmt.Errorf("accessrequests.Create write: %w", err)
	}
	return req, nil
}

// Get retrieves a single access request by ID.
// Returns ErrNotFound when the ID does not exist.
func (s *Store) Get(id string) (*AccessRequest, error) {
	fields, err := s.rdb.HGetAll(context.Background(), arKey(id)).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.Get %q: %w", id, err)
	}
	if len(fields) == 0 {
		return nil, ErrNotFound
	}
	return arFromHash(fields)
}

// ListAll returns every stored access request, newest first.
func (s *Store) ListAll() ([]*AccessRequest, error) {
	return s.listFromIndex(arAllKey)
}

// ListPending returns only requests with status=pending, newest first.
func (s *Store) ListPending() ([]*AccessRequest, error) {
	return s.listFromIndex(arPendingKey)
}

// ListByStatus returns requests with the given status, newest first.
func (s *Store) ListByStatus(status Status) ([]*AccessRequest, error) {
	if status == StatusPending {
		return s.ListPending()
	}
	all, err := s.ListAll()
	if err != nil {
		return nil, err
	}
	out := make([]*AccessRequest, 0, len(all))
	for _, req := range all {
		if req.Status == status {
			out = append(out, req)
		}
	}
	return out, nil
}

// ListForUser returns all requests submitted by userID, newest first.
func (s *Store) ListForUser(userID string) ([]*AccessRequest, error) {
	return s.listFromIndex(arUserKey(userID))
}

// ListActiveServiceUIDs returns service UIDs currently granted to userID by
// approved, unexpired access requests.
func (s *Store) ListActiveServiceUIDs(userID string, now time.Time) (map[string]struct{}, error) {
	reqs, err := s.ListForUser(userID)
	if err != nil {
		return nil, err
	}
	type candidate struct {
		req *AccessRequest
		cmd *redis.StringCmd
	}
	candidates := make([]candidate, 0, len(reqs))
	for _, req := range reqs {
		if !req.ActiveApproved(now) || req.ServiceUID == "" {
			continue
		}
		candidates = append(candidates, candidate{req: req})
	}
	if len(candidates) == 0 {
		return map[string]struct{}{}, nil
	}

	ctx := context.Background()
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		for i := range candidates {
			candidates[i].cmd = pipe.Get(ctx, arActiveKey(candidates[i].req.UserID, candidates[i].req.ServiceUID))
		}
		return nil
	})
	if err != nil && !errors.Is(err, redis.Nil) {
		return nil, fmt.Errorf("accessrequests.ListActiveServiceUIDs active lookup: %w", err)
	}

	active := make(map[string]struct{})
	for _, c := range candidates {
		activeID, err := c.cmd.Result()
		if errors.Is(err, redis.Nil) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("accessrequests.ListActiveServiceUIDs active result: %w", err)
		}
		if activeID == c.req.ID {
			active[c.req.ServiceUID] = struct{}{}
		}
	}
	return active, nil
}

func (s *Store) listFromIndex(indexKey string) ([]*AccessRequest, error) {
	ctx := context.Background()
	ids, err := s.rdb.ZRangeArgs(ctx, redis.ZRangeArgs{
		Key:   indexKey,
		Start: 0,
		Stop:  -1,
		Rev:   true,
	}).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.list %q: %w", indexKey, err)
	}
	if len(ids) == 0 {
		return []*AccessRequest{}, nil
	}
	cmds := make([]*redis.MapStringStringCmd, len(ids))
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		for i, id := range ids {
			cmds[i] = pipe.HGetAll(ctx, arKey(id))
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("accessrequests.list fetch: %w", err)
	}
	out := make([]*AccessRequest, 0, len(ids))
	for _, cmd := range cmds {
		fields, err := cmd.Result()
		if err != nil || len(fields) == 0 {
			continue
		}
		r, err := arFromHash(fields)
		if err != nil {
			continue
		}
		out = append(out, r)
	}
	return out, nil
}

// Resolve transitions an access request to Approved, Denied, or Revoked and
// records who performed the resolution. Returns the updated request.
// Returns ErrNotFound when the ID does not exist.
func (s *Store) Resolve(id string, resolution Resolution) (*AccessRequest, error) {
	if resolution.Status != StatusApproved && resolution.Status != StatusDenied && resolution.Status != StatusRevoked {
		return nil, ErrInvalidStatus
	}
	ctx := context.Background()
	// Fetch the full record so we can clean up the dedup key.
	fields, err := s.rdb.HGetAll(ctx, arKey(id)).Result()
	if err != nil {
		return nil, fmt.Errorf("accessrequests.Resolve get: %w", err)
	}
	if len(fields) == 0 {
		return nil, ErrNotFound
	}
	req, err := arFromHash(fields)
	if err != nil {
		return nil, err
	}
	now := time.Now().UTC()
	req.Status = resolution.Status
	req.ResolvedAt = &now
	req.ResolvedBy = resolution.ResolvedBy
	req.ResolvedByName = resolution.ResolvedByName
	req.ResolvedByEmail = resolution.ResolvedByEmail
	req.ExpiresAt = nil
	if resolution.Status == StatusApproved && resolution.ExpiresAt != nil {
		exp := resolution.ExpiresAt.UTC()
		req.ExpiresAt = &exp
	}
	resolvedAtStr := now.Format(time.RFC3339Nano)
	activeKey := arActiveKey(req.UserID, req.ServiceUID)
	_, err = s.rdb.Pipelined(ctx, func(pipe redis.Pipeliner) error {
		pipe.HSet(ctx, arKey(id),
			"status", string(resolution.Status),
			"resolvedAt", resolvedAtStr,
			"resolvedBy", resolution.ResolvedBy,
			"resolvedByName", resolution.ResolvedByName,
			"resolvedByEmail", resolution.ResolvedByEmail,
		)
		if req.ExpiresAt != nil {
			pipe.HSet(ctx, arKey(id), "expiresAt", req.ExpiresAt.Format(time.RFC3339Nano))
		} else {
			pipe.HDel(ctx, arKey(id), "expiresAt")
		}
		if req.Status == StatusApproved && req.ExpiresAt != nil {
			if ttl := req.ExpiresAt.Sub(now); ttl > 0 {
				pipe.Set(ctx, activeKey, req.ID, ttl)
			} else {
				pipe.Eval(ctx, deleteActiveIfMatchesScript, []string{activeKey}, req.ID)
			}
		} else {
			// Resolving to denied/revoked clears this request's entitlement for
			// the user/service pair. The compare prevents an old request from
			// deleting a newer active approval for the same target.
			pipe.Eval(ctx, deleteActiveIfMatchesScript, []string{activeKey}, req.ID)
		}
		// Remove from pending index; keep in all + user indexes.
		pipe.ZRem(ctx, arPendingKey, id)
		// Release the dedup lock so a future request can be created.
		pipe.Del(ctx, arDedupKey(req.UserID, req.ServiceUID))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("accessrequests.Resolve write: %w", err)
	}
	return req, nil
}

// ActiveApproved reports whether this record currently grants service access.
func (r *AccessRequest) ActiveApproved(now time.Time) bool {
	if r == nil || r.Status != StatusApproved {
		return false
	}
	if r.ExpiresAt == nil || !r.ExpiresAt.After(now) {
		return false
	}
	return true
}

// --- helpers ---

func arKey(id string) string         { return arHashPrefix + id }
func arUserKey(userID string) string { return arUserPrefix + userID }
func arDedupKey(userID, svcUID string) string {
	return arDedupPrefix + userID + ":" + svcUID
}
func arActiveKey(userID, svcUID string) string {
	return arActivePrefix + userID + ":" + svcUID
}

func arFromHash(f map[string]string) (*AccessRequest, error) {
	reqAt, err := time.Parse(time.RFC3339Nano, f["requestedAt"])
	if err != nil {
		return nil, fmt.Errorf("parse requestedAt: %w", err)
	}
	req := &AccessRequest{
		ID:          f["id"],
		ServiceUID:  f["serviceUID"],
		ServiceName: f["serviceName"],
		TargetOwner: f["targetOwner"],
		UserID:      f["userID"],
		UserEmail:   f["userEmail"],
		Message:     f["message"],
		Status:      Status(f["status"]),
		RequestedAt: reqAt,
	}
	if s := f["resolvedAt"]; s != "" {
		t, err := time.Parse(time.RFC3339Nano, s)
		if err != nil {
			return nil, fmt.Errorf("parse resolvedAt: %w", err)
		}
		req.ResolvedAt = &t
	}
	req.ResolvedBy = f["resolvedBy"]
	req.ResolvedByName = f["resolvedByName"]
	req.ResolvedByEmail = f["resolvedByEmail"]
	if s := f["expiresAt"]; s != "" {
		t, err := time.Parse(time.RFC3339Nano, s)
		if err != nil {
			return nil, fmt.Errorf("parse expiresAt: %w", err)
		}
		req.ExpiresAt = &t
	}
	return req, nil
}
