name: Add to project

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  sync:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.user.login != 'dependabot[bot]' }}
    uses: nebari-dev/.github/.github/workflows/sync-project-priority.yaml@main
    with:
      project-id: PVT_kwDOBd3CI84BKoKt
    secrets:
      token: ${{ secrets.ADD_TO_PROJECT_PAT }}
